mealPlanner/mealPlanner/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

mealPlanner/polls/urls.py
from django.urls import path, include
from django.contrib import admin

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.user_view, name='index'),
    path('ingredients/', views.ing_view, name='ingredients'),
    path('units/', views.unit_view, name='units'),
    path('shop-list/', views.list_view, name='shoplist'),
    path('<int:meal_id>/', views.meal_view, name='detail'),
]

mealPlanner/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Ingredient(models.Model):
    ingredient_name = models.CharField(max_length=50)

    def __str__(self):
        return self.ingredient_name
    

class Unit(models.Model):
    unit = models.CharField(max_length=20)

    def __str__(self):
        return self.unit
    

class Meal(models.Model):
    meal_name = models.CharField(max_length=50)

    def __str__(self):
        return self.meal_name


class MealIngredient(models.Model):
    meal = models.ForeignKey(Meal, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    quantity = models.IntegerField(default = 0)
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.meal) + " "+str(self.ingredient)+" "+str(self.quantity)+str(self.unit)

mealPlanner/polls/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils.datastructures import MultiValueDictKeyError

from .models import Meal, Ingredient, MealIngredient, Unit
from .generate_list import generate

def user_view(request):
    if request.method == "POST":
        name = request.POST['newmeal']
        test = name.strip()
        if len(test) != 0:
            meal = Meal(meal_name=name)
            meal.save()
        return HttpResponseRedirect(reverse('polls:index'))
    

    meals = Meal.objects.order_by('meal_name')
    print(meals)

    return render(request, 'polls/index.html', {'alphabetical_meals_list':meals})

def list_view(request):
    meals = []
    for key, value in request.POST.items():
        try:
            value = int(value)
        except ValueError:
            continue
        
        meals.append(Meal.objects.get(pk=int(value)))
    ingredients = generate(meals)
    print(ingredients)

    return render(request, 'polls/shoppinglist.html', {"ingredient_list":ingredients})
    
    


def ing_view(request):
    if request.method == "POST":
        name = request.POST['newing']
        test = name.split()
        if len(test) != 0:
            ing = Ingredient(ingredient_name=name)
            ing.save()
        return HttpResponseRedirect(reverse('polls:ingredients'))
    

    ings = Ingredient.objects.order_by('ingredient_name')

    return render(request, 'polls/ingredients.html', {'ings':ings})       


def unit_view(request):
    if request.method == "POST":
        name = request.POST['newunit']
        test = name.split()
        if len(test) != 0:
            unit = Unit(unit=name)
            unit.save()
        return HttpResponseRedirect(reverse('polls:units'))
    

    un = Unit.objects.order_by('unit')

    return render(request, 'polls/units.html', {'units':un})       




def meal_view(request, meal_id):

    if request.method == "POST":
        qty = request.POST['qty']
        test = qty.split()
        if len(test) != 0:
            try:
                ingredient = request.POST['ingredient']
                unit = request.POST['unit']
                meal = Meal.objects.get(pk=meal_id)
                added_ingredient = MealIngredient(meal=meal, ingredient=Ingredient.objects.get(pk=ingredient), quantity=int(qty), unit=Unit.objects.get(pk=unit))
                added_ingredient.save()
            except MultiValueDictKeyError:
                pass
        return HttpResponseRedirect(reverse('polls:detail', args=(meal_id,)))

    try:
        ingredients = MealIngredient.objects.filter(meal=meal_id)
        alling = Ingredient.objects.all()
        allunits = Unit.objects.all()
        meal = Meal.objects.get(pk=meal_id)
    except MealIngredient.DoesNotExist:
        raise Http404("There is no such meal!")

    return render(request, 'polls/detail.html', {'meal':meal, 'mi':ingredients, 'ing':alling, 'units':allunits})

mealPlanner/polls/templates/polls/detail.html
{% load static %}
<head>
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link" href="{% url 'polls:index' %}">Home</a>
            <a class="nav-item nav-link" href="{% url 'polls:ingredients' %}">Add Ingredient</a>
            <a class="nav-item nav-link" href="{% url 'polls:units' %}">Add Unit</a>
        </div>
    </div>
</nav>
<h1>{{ meal.meal_name }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% csrf_token %}
<ul>
{% for i in mi %}
    <li>{{ i.ingredient.ingredient_name }} {{i.quantity}} {{i.unit}}</li>
{% endfor %}
</ul>

<form method = "POST" action="{% url 'polls:detail' meal.id %}">
{% csrf_token %}
    <select name ="ingredient">
        {% for i in ing %}
            <option value={{i.pk}}>{{ i.ingredient_name }} </option>
        {% endfor %}
    </select>
    <input name="qty" type="number" min="0" step="1">
    <select name ="unit">
        {% for u in units %}
            <option value={{u.pk}}>{{ u.unit }} </option>
        {% endfor %}
    </select>
    <button type="submit">Add</button>
</form>

</body>

mealPlanner/polls/templates/polls/index.html
{% load static %}

<head>
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>
<script>
function validateForm() {
  var x = document.forms["form"]["make"].value;
  if (x == "") {
    alert("Name must be filled out");
    return false;
  }
}
</script>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link" href="{% url 'polls:index' %}">Home</a>
            <a class="nav-item nav-link" href="{% url 'polls:ingredients' %}">Add Ingredient</a>
            <a class="nav-item nav-link" href="{% url 'polls:units' %}">Add Unit</a>
        </div>
    </div>
</nav>
{% if alphabetical_meals_list %}
    <form name = "form" method = "POST" action="{% url 'polls:shoplist' %}">
    {% csrf_token %}
    {% for meal in alphabetical_meals_list %}
        <input type="checkbox" name="Meal{{meal.id}}" value="{{meal.id}}">
        <label for="Meal{{meal.id}}"><a href="{% url 'polls:detail' meal.id %}">{{ meal.meal_name }}</a></label>
        </br>
    {% endfor %}
    <button type="submit">Generate List</button>
    </form>
{% else %}
    <p>You have not made any meals.</p>
{% endif %}
<form method = "POST" action="{% url 'polls:index' %}">
{% csrf_token %}
    <input onsubmit="return validateForm()" type="text" name ="newmeal" placeholder ="Add meal here" required></input>
    <button type="submit" name="make">Make</button>
</form>
</body>

mealPlanner/polls/templates/polls/ingredients.html
{% load static %}

<head>
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link" href="{% url 'polls:index' %}">Home</a>
            <a class="nav-item nav-link" href="{% url 'polls:ingredients' %}">Add Ingredient</a>
            <a class="nav-item nav-link" href="{% url 'polls:units' %}">Add Unit</a>
        </div>
    </div>
</nav>
{% if ings %}
    <ul>
    {% for i in ings %}
        <li>{{ i.ingredient_name }}</li>
    {% endfor %}
    </ul>
        
{% else %}
    <p>You have not made any ingredients.</p>
{% endif %}
<form method = "POST" action="{% url 'polls:ingredients' %}">
{% csrf_token %}
    <input type="text" name ="newing" placeholder ="Add ingredient here"></input>
    <button type="submit">Make</button>
</form>
</body>

mealPlanner/polls/templates/polls/shoppinglist.html
{% load static %}

<head>
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link" href="{% url 'polls:index' %}">Home</a>
            <a class="nav-item nav-link" href="{% url 'polls:ingredients' %}">Add Ingredient</a>
            <a class="nav-item nav-link" href="{% url 'polls:units' %}">Add Unit</a>
        </div>
    </div>
</nav>
<h1>Your Personalised Shopping List</h1>
<ul>
    {% for ingredient in ingredient_list %}
        <li>{% for item in ingredient%}
            {{item}}
        {% endfor %}</li>
    {% endfor %}
</ul>
</body>

mealPlanner/polls/templates/polls/units.html
{% load static %}

<head>
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link" href="{% url 'polls:index' %}">Home</a>
            <a class="nav-item nav-link" href="{% url 'polls:ingredients' %}">Add Ingredient</a>
            <a class="nav-item nav-link" href="{% url 'polls:units' %}">Add Unit</a>
        </div>
    </div>
</nav>
{% if units %}
    <ul>
    {% for i in units %}
        <li>{{ i.unit }}</li>
    {% endfor %}
    </ul>
        
{% else %}
    <p>You have not made any ingredients.</p>
{% endif %}
<form method = "POST" action="{% url 'polls:units' %}">
{% csrf_token %}
    <input type="text" name ="newunit" placeholder ="Add unit here"></input>
    <button type="submit">Make</button>
</form>
</body>